Minor cleanup

diff --git a/network-irq-affinity b/network-irq-affinity
--- a/network-irq-affinity
+++ b/network-irq-affinity
@@ -1,5 +1,4 @@
 #!/bin/sh
-# @(#)$KimmoSuominen$
 #
 # Copyright (c) 2017 Kimmo Suominen
 # All rights reserved.
@@ -106,7 +105,7 @@ network_irqs()
 
 set_affinity()
 {
-    local cpu irq list que
+    local cpu file irq que
 
     irq="${1}"
     cpu="${2}"
@@ -127,16 +126,14 @@ set_affinity()
 	cpu=0
     fi
     verbose "Assigning ${que} on IRQ ${irq} to CPU ${cpu}"
-    if ${noop}
+    if ! ${noop}
     then
-	:
-    else
-	list="/proc/irq/${irq}/smp_affinity_list"
-	if [ -w "${list}" ]
+	file="/proc/irq/${irq}/smp_affinity_list"
+	if [ -w "${file}" ]
 	then
-	    echo "${cpu}" > "${list}"
+	    echo "${cpu}" > "${file}"
 	else
-	    fatal "Cannot write to '${list}'"
+	    fatal "Cannot write to '${file}'"
 	fi
     fi
 }
